// MathForge — Opportunities data
//
// This file backs the /opportunities/ page (competitions, olympiads and,
// eventually, essay prizes and other mathematical opportunities).
//
// tier: which student stage(s) this fits — drives the Level filter.
//       "middle" | "high" | "university" — an entry can belong to more than one.
// format: "online" | "onsite" — drives the Format filter.
// region: display string for where it's held / who it's open to. Also the
//         source string the Country/Region filter groups on (see countryGroup()
//         in the page script) — don't remove or shorten it, the grouping reads it.
// costType: "free" | "paid" — drives the Cost filter. costNote is the display string.
// participationType: "individual" | "team" — drives the Individual/Team filter.
//         Read off each entry's own description (team size, "solved independently",
//         etc.) — never guessed.
// category: "competition" | "essay" — drives future Subject-adjacent scaling.
//         Everything here is "competition" today; essay prizes will be added as
//         MathForge curates them, not invented ahead of time.
// entryType:
//   "open"          → public registration with a real deadline; status badge
//                      (Open / Closing Soon / Closed) computed from regCloses.
//   "discretionary" → school or institution enters students; no public deadline.
//   "qualification" → invitation-only, earned via a prior round; no public deadline.
// seal: 2–4 character monogram shown in the seal badge (kept short on purpose).
//       Used as a fallback whenever `logo` is absent or fails to load.
// logo: optional URL to the organiser's own logo image, shown in place of the
//       seal monogram on the card. Omit entirely until a real asset exists —
//       never point it at a placeholder or guessed path.
// lastVerified: optional "YYYY-MM-DD" — the date MathForge last confirmed this
//       entry's details against the organiser's own site. Shown on the card as
//       "Verified D MMM YYYY" when present. Omit entirely rather than guessing —
//       do not backfill a date just because the entry itself looks current.
// whyRecommend: MathForge's own editorial note — optional. Only written where it
//         is directly supported by the entry's own fields (cost, format, entry
//         route, description). Omitted rather than guessed for entries where
//         MathForge doesn't have a real basis for a recommendation (e.g. pure
//         qualification rounds a student can't directly enter).
//
// Do NOT invent regOpens/regCloses for discretionary or qualification entries — there
// isn't a public one. If an "open" entry's real deadline hasn't been published yet, set
// regCloses to null and datesTBA: true rather than guessing.

const opportunities = [
  {
    id: "mog-mcg-2026",
    seal: "MOG",
    name: "Mathematical Olympiad / Competition for Girls",
    org: "UKMT",
    region: "United Kingdom",
    level: "Year 12/13",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "Small school entry fee",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-09-22",
    entryType: "discretionary",
    description: "Five Olympiad-style problems, for girls and young women.",
    whyRecommend: "A respected, proof-based entry point aimed specifically at girls and young women in the UK Olympiad pipeline.",
    url: "https://ukmt.org.uk/mathematical-olympiad-for-girls",
    difficulty: "hard"
  },
  {
    id: "iymc-qualification-2026",
    seal: "IY",
    name: "International Youth Math Challenge — Qualification Round",
    org: "IYMC",
    region: "Global",
    level: "High school & university (Junior / Youth / Senior)",
    tier: ["high", "university"],
    format: "online",
    costType: "free",
    costNote: "Free",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-09-27",
    regOpens: null,
    regCloses: "2026-09-27",
    entryType: "open",
    description: "Five problems, solved independently and submitted online; scoring the required threshold advances you to the Pre-Final Round.",
    whyRecommend: "Free, online, and open worldwide — a low-friction way to test yourself against an international field.",
    url: "https://iymc.info/",
    difficulty: "standard"
  },
  {
    id: "smc-2026",
    seal: "SMC",
    name: "Senior Mathematical Challenge",
    org: "UKMT",
    region: "United Kingdom",
    level: "Year 13 and below",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "~£3 per student (school-administered)",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-10-07",
    regOpens: null,
    regCloses: "2026-10-07",
    entryType: "open",
    description: "90-minute first-round challenge: 22 multiple-choice + 3 integer-answer questions.",
    whyRecommend: "The standard, low-cost first step into the UK Olympiad pipeline — ask your school to enter you.",
    url: "https://ukmt.org.uk/senior-challenges/senior-mathematical-challenge",
    difficulty: "standard"
  },
  {
    id: "amc-10-12-a-2026",
    seal: "AMC",
    name: "AMC 10/12 A",
    org: "MAA",
    region: "USA & Canada (int'l sites accepted)",
    level: "Grade 12 and below",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "~$40 school competition fee",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-11-05",
    regOpens: null,
    regCloses: "2026-10-28",
    entryType: "open",
    description: "75-minute, 25-question multiple-choice contest; qualifying scorers invited to AIME.",
    whyRecommend: "A well-known US benchmark; strong scorers advance to the AIME, which feeds the US Olympiad pipeline.",
    url: "https://maa.org/student-programs/amc/",
    difficulty: "hard"
  },
  {
    id: "amc-10-12-b-2026",
    seal: "AMC",
    name: "AMC 10/12 B",
    org: "MAA",
    region: "USA & Canada (int'l sites accepted)",
    level: "Grade 12 and below",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "~$40 school competition fee",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-11-13",
    regOpens: null,
    regCloses: "2026-10-28",
    entryType: "open",
    description: "Second sitting of the AMC 10/12, same format and rules as the A paper.",
    whyRecommend: "Worth it if the A-paper date clashes with school, or as a second attempt at the same benchmark.",
    url: "https://maa.org/student-programs/amc/",
    difficulty: "hard"
  },
  {
    id: "hmmt-november-2026",
    seal: "HM",
    name: "Harvard-MIT Mathematics Tournament — November",
    org: "HMMT",
    region: "USA (int'l teams accepted)",
    level: "High school",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "Per-team registration fee",
    participationType: "team",
    category: "competition",
    eventDate: "2026-11-07",
    regOpens: null,
    regCloses: "2026-09-20",
    entryType: "open",
    description: "On-campus tournament at Harvard — individual subject tests, a team round, and the signature Guts round; acceptance is by lottery.",
    whyRecommend: "One of the most prestigious team tournaments a high schooler can attend — build a team and register early, entry is by lottery.",
    url: "https://www.hmmt.org/",
    difficulty: "elite"
  },
  {
    id: "bmo1-2026",
    seal: "BMO",
    name: "British Mathematical Olympiad Round 1",
    org: "UKMT",
    region: "United Kingdom",
    level: "Year 13 and below",
    tier: ["high"],
    format: "onsite",
    costType: "free",
    costNote: "Free",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-11-18",
    entryType: "qualification",
    description: "3.5-hour, six-question Olympiad-style paper.",
    url: "https://ukmt.org.uk/senior-challenges/british-maths-olympiad-round-1",
    difficulty: "elite"
  },
  {
    id: "senior-kangaroo-2026",
    seal: "SK",
    name: "Andrew Jobbings Senior Kangaroo",
    org: "UKMT",
    region: "United Kingdom",
    level: "Year 13 and below",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "Small entry fee",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-11-18",
    entryType: "qualification",
    description: "60-minute, 20-question integer-answer follow-on to the SMC.",
    url: "https://ukmt.org.uk/senior-challenges/andrew-jobbings-senior-kangaroo",
    difficulty: "hard"
  },
  {
    id: "bmo2-2027",
    seal: "BMO",
    name: "British Mathematical Olympiad Round 2",
    org: "UKMT",
    region: "United Kingdom",
    level: "Year 13 and below",
    tier: ["high"],
    format: "onsite",
    costType: "free",
    costNote: "Free",
    participationType: "individual",
    category: "competition",
    eventDate: "2027-01-20",
    entryType: "qualification",
    description: "Entry point to the UK's training and selection programme for international competitions.",
    url: "https://ukmt.org.uk/senior-challenges/british-maths-olympiad-round-2",
    difficulty: "elite"
  },
  {
    id: "hmmt-february-2027",
    seal: "HM",
    name: "Harvard-MIT Mathematics Tournament — February",
    org: "HMMT",
    region: "USA (int'l teams accepted)",
    level: "High school",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "Per-team registration fee",
    participationType: "team",
    category: "competition",
    eventDate: "2027-02-13",
    regOpens: null,
    regCloses: "2026-09-20",
    entryType: "open",
    description: "The harder of the two HMMT tournaments, held at MIT, with problems ranging up to Olympiad level.",
    whyRecommend: "The harder of the two HMMT sittings — worth targeting once your team has a November result to build on.",
    url: "https://www.hmmt.org/",
    difficulty: "elite"
  },
  {
    id: "smt-online-2027",
    seal: "SMT",
    name: "Stanford Math Tournament — Online",
    org: "SUMO / Stanford",
    region: "Global",
    level: "High school (teams of 5–8)",
    tier: ["high"],
    format: "online",
    costType: "paid",
    costNote: "Team registration fee",
    participationType: "team",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    regOpens: null,
    regCloses: null,
    entryType: "open",
    description: "Remote division of SMT, open to teams worldwide — individual subject tests plus Team, Power, and Guts rounds.",
    whyRecommend: "A Stanford-run team tournament with no travel required — a good stepping stone before an on-campus event.",
    url: "https://www.stanfordmathtournament.org/",
    difficulty: "hard"
  },
  {
    id: "purple-comet-2027",
    seal: "PC",
    name: "Purple Comet! Math Meet",
    org: "AwesomeMath",
    region: "Global",
    level: "Middle & high school (teams of 1–6)",
    tier: ["middle", "high"],
    format: "online",
    costType: "free",
    costNote: "Free",
    participationType: "team",
    category: "competition",
    eventDate: "2027-04-15",
    regOpens: "2027-02-01",
    regCloses: "2027-04-15",
    entryType: "open",
    description: "Free, online team contest — pick any start time within the ten-day window and solve 20 (middle school) or 30 (high school) problems.",
    whyRecommend: "Free international team competition with no travel requirement — an excellent first team event.",
    url: "https://purplecomet.org/",
    difficulty: "hard"
  },
  {
    id: "math-kangaroo-2027",
    seal: "MK",
    name: "Math Kangaroo",
    org: "AKSF",
    region: "Global (90+ countries, incl. Pakistan)",
    level: "Grades 1–12",
    tier: ["middle", "high"],
    format: "onsite",
    costType: "paid",
    costNote: "~$18–25 (varies by country)",
    participationType: "individual",
    category: "competition",
    eventDate: "2027-03-18",
    regOpens: "2026-09-15",
    regCloses: "2026-12-31",
    entryType: "open",
    description: "The world's largest school math competition — a single 75-minute multiple-choice test rewarding logic and creative problem-solving over rote calculation.",
    whyRecommend: "Low-cost, widely available, and a gentler format for building competition experience early.",
    url: "https://mathkangaroo.org/",
    difficulty: "standard"
  },
  {
    id: "putnam-2026",
    seal: "PUT",
    name: "William Lowell Putnam Mathematical Competition",
    org: "MAA",
    region: "USA & Canada",
    level: "Undergraduate (no degree yet held)",
    tier: ["university"],
    format: "onsite",
    costType: "free",
    costNote: "Free (run through your institution)",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-12-05",
    entryType: "discretionary",
    description: "The most prestigious university-level math exam in North America — twelve brutal proof-based problems in two sittings; a median score of 0–2 out of 120 is normal.",
    whyRecommend: "The benchmark undergraduate proof competition in North America — free through your institution, and a median score of 0–2 is genuinely normal.",
    url: "https://maa.org/putnam/",
    difficulty: "elite"
  },
  {
    id: "pmo-2026",
    seal: "PMO",
    name: "Pakistan Mathematics Olympiad",
    org: "FBISE / LUMS",
    region: "Pakistan",
    level: "SSC/O Level & HSSC/A Level",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "PKR 1,000",
    participationType: "individual",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    regOpens: null,
    regCloses: null,
    entryType: "open",
    description: "Pakistan's national mathematics Olympiad, run by FBISE with a LUMS-designed syllabus — open to O Level and A Level students nationwide, with cash prizes, medals, and university scholarships for top scorers.",
    whyRecommend: "Pakistan's own national Olympiad, with a low entry fee and university scholarships for top scorers — worth entering locally before looking abroad.",
    url: "https://www.fbise.edu.pk/pmo.php",
    difficulty: "hard"
  },
  {
    id: "aime-2027",
    seal: "AIME",
    name: "American Invitational Mathematics Examination",
    org: "MAA",
    region: "USA & Canada (int'l sites accepted)",
    level: "Qualifiers from AMC 10/12",
    tier: ["high"],
    format: "onsite",
    costType: "free",
    costNote: "No additional fee for qualifiers",
    participationType: "individual",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    entryType: "qualification",
    description: "15-question, 3-hour invitational exam for AMC 10/12 top scorers, with integer answers from 0–999; strong scores lead to USAMO/USAJMO qualification.",
    url: "https://maa.org/maa-invitational-competitions/",
    difficulty: "elite"
  },
  {
    id: "euclid-2027",
    seal: "EUC",
    name: "Euclid Contest",
    org: "CEMC / University of Waterloo",
    region: "Global (school-administered, accepted worldwide)",
    level: "Grade 12 (strong younger students also welcome)",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "School order fee (varies by country)",
    participationType: "individual",
    category: "competition",
    eventDate: "2027-04-07",
    regOpens: null,
    regCloses: "2027-03-11",
    entryType: "open",
    description: "150-minute, 10-question senior contest mixing short-answer and full-solution problems — held one day earlier in North & South America than elsewhere.",
    whyRecommend: "A globally accepted, school-administered contest that carries real weight for University of Waterloo admissions and STEM scholarships.",
    url: "https://cemc.uwaterloo.ca/contests/euclid",
    difficulty: "hard"
  },
  {
    id: "simon-marais-2026",
    seal: "SMMC",
    name: "Simon Marais Mathematics Competition",
    org: "Simon Marais Mathematics Competition Ltd",
    region: "Asia-Pacific & global (university-administered)",
    level: "Undergraduate",
    tier: ["university"],
    format: "onsite",
    costType: "free",
    costNote: "Free for participating universities (fee above 50 entrants)",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-10-10",
    entryType: "discretionary",
    description: "Modelled on the Putnam — challenging proof-based problems for undergraduates across Asia-Pacific and beyond, entered individually or in pairs through a university coordinator.",
    whyRecommend: "The Asia-Pacific undergraduate counterpart to the Putnam — ask your university's mathematics department whether it takes part.",
    url: "https://www.simonmarais.org/",
    difficulty: "elite"
  },
  {
    id: "copernicus-math-olympiad-2026",
    seal: "COP",
    name: "Copernicus Mathematics Olympiad",
    org: "Copernicus Olympiad",
    region: "Global (54+ countries, via country representatives)",
    level: "Grades 2–12",
    tier: ["middle", "high"],
    format: "online",
    costType: "paid",
    costNote: "Registration fee (varies by country representative)",
    participationType: "individual",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    regOpens: null,
    regCloses: null,
    entryType: "open",
    description: "Two-stage international olympiad — an online Preliminary Round followed by an invitational Global Round for top scorers, open to students from Grade 2 through 12.",
    whyRecommend: "A genuinely global preliminary round you can sit from home, with a real shot at an invitation to the in-person Global Round for strong scorers.",
    url: "https://copernicusolympiad.us/mathematics-olympiad/",
    difficulty: "standard"
  },
  {
    id: "seamo-x-2027",
    seal: "SEA",
    name: "Southeast Asian Mathematical Olympiad (SEAMO X)",
    org: "SEAMO",
    region: "Global (22+ countries; finals in Thailand)",
    level: "Grades 1–12 (Papers K, A–F)",
    tier: ["middle", "high"],
    format: "online",
    costType: "paid",
    costNote: "Entry fee (varies by country)",
    participationType: "individual",
    category: "competition",
    eventDate: "2027-01-15",
    regOpens: null,
    regCloses: null,
    datesTBA: true,
    entryType: "open",
    description: "A first-round paper (timing varies by country) feeds into SEAMO X, the Champions/Open Division world final, held 15–18 January 2027 in Bangkok, Thailand.",
    whyRecommend: "A well-established regional olympiad with a genuine international final — check your country's first-round window with a local SEAMO representative.",
    url: "https://seamo-official.org/",
    difficulty: "standard"
  },
  {
    id: "yimo-2026",
    seal: "YIMO",
    name: "Youth International Math Olympiad (YIMO)",
    org: "STEMise / NXT Horizon",
    region: "Global (fully online)",
    level: "Middle & high school (Rising Stars / High Achievers)",
    tier: ["middle", "high"],
    format: "online",
    costType: "free",
    costNote: "Free",
    participationType: "individual",
    category: "competition",
    eventDate: "2026-08-29",
    regOpens: null,
    regCloses: "2026-08-27",
    entryType: "open",
    description: "Free, single-window online contest — 20 written problems mixing multiple-choice and AIME-style integer answers, with top scorers in each division advancing to a proof-based final round.",
    whyRecommend: "Completely free and fully online, with a genuine final round for top performers — a low-risk way to test AIME-level problem-solving.",
    url: "https://www.yimo-official.org/",
    difficulty: "hard"
  },
  {
    id: "sigma-lums-2027",
    seal: "SIG",
    name: "SIGMA — LUMS Mathematics Olympiad",
    org: "LUMS Students' Mathematics Society (LSMS)",
    region: "Pakistan",
    level: "High school & university teams",
    tier: ["high", "university"],
    format: "onsite",
    costType: "paid",
    costNote: "Small per-team registration fee",
    participationType: "team",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    entryType: "open",
    description: "LUMS's flagship three-day mathematics olympiad — teams from across Pakistan compete in a mix of speed rounds, logic puzzles, and problem-solving events like the LUMS Integration Bee.",
    whyRecommend: "One of Pakistan's biggest student-run maths events — a fun, team-based alternative to solo Olympiad prep.",
    url: "https://lsms.lums.edu.pk/sigma.html",
    difficulty: "standard"
  },
  {
    id: "nust-math-olympiad-2026",
    seal: "NUST",
    name: "NUST Mathematics Olympiad",
    org: "National University of Sciences & Technology (NUST)",
    region: "Pakistan",
    level: "Undergraduate (Physics, Maths, Engineering, CS, Data Science)",
    tier: ["university"],
    format: "onsite",
    costType: "paid",
    costNote: "Small registration fee",
    participationType: "team",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    entryType: "open",
    description: "University-level olympiad open to BS students in Physics, Mathematics, Engineering, Computer Science, and Data Science/Statistics — enter solo or in teams of up to three.",
    whyRecommend: "A strong national university-level contest for STEM undergrads in Pakistan, with flexible solo or small-team entry.",
    url: "https://nust.edu.pk/events/register-now-for-nust-mathematics-olympiad/",
    difficulty: "hard"
  },
  {
    id: "nstc-nmtc-2026",
    seal: "NSTC",
    name: "National Mathematics Talent Contest (NSTC — Road to IMO)",
    org: "STEM Careers Program (HEC & PIEAS)",
    region: "Pakistan",
    level: "Matric/O-Level Part-I or FSc/A-Level Part-I (60%+ aggregate in Maths, Physics, Chemistry & Biology)",
    tier: ["high"],
    format: "onsite",
    costType: "paid",
    costNote: "Rs 1,000 non-refundable application fee",
    participationType: "individual",
    category: "competition",
    eventDate: null,
    datesTBA: true,
    regOpens: null,
    regCloses: null,
    entryType: "open",
    description: "Pakistan's national talent-and-training pipeline to the International Mathematical Olympiad — a screening test followed by training camps, with the top six representing Pakistan at the IMO.",
    whyRecommend: "The official route onto Pakistan's IMO team — the highest-stakes pathway on this list for a student serious about international Olympiad selection.",
    url: "https://stem.edu.pk/nstc/",
    difficulty: "elite"
  }
];
